# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-06 08:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_auto_20180506_0755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ('-published_date',)},
        ),
    ]
